import type { Metadata } from "next";
import { LegalPage } from "../legal-layout";

export const metadata: Metadata = {
  title: "Terms of Service — MyWorkFlo",
  description: "The terms that govern use of MyWorkFlo.",
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="September 22, 2026">
      <p>
        These terms govern use of MyWorkFlo — the website at myworkflo.com and the application at
        app.myworkflo.com — by the home-service businesses that subscribe to it (&ldquo;you&rdquo;). By
        creating an account or using the service you agree to these terms.
      </p>

      <h2>The service</h2>
      <p>
        MyWorkFlo answers missed calls by text on your behalf: it collects service-request details from your
        customers, drafts or sends replies according to the control mode you choose, books appointments, and
        escalates to your staff. You choose how much autonomy the AI has (Draft, Assisted, or Autopilot) and
        you can change it at any time — with one exception below.
      </p>

      <h2>Safety messages</h2>
      <p>
        When a conversation indicates a possible safety emergency (for example a gas smell or carbon
        monoxide concern), MyWorkFlo immediately sends a fixed, pre-approved safety message advising the
        person to get to safety and call 911, notifies your staff, and marks the conversation urgent — in
        every control mode, including Draft. These safety scripts are not configurable. MyWorkFlo is a
        communication tool, not an emergency service, and does not provide medical, safety, or repair advice.
      </p>

      <h2>Your responsibilities</h2>
      <ul>
        <li>Provide accurate business information, hours, service area, and pricing guidance.</li>
        <li>
          Use the service only with phone numbers you are entitled to use, and comply with applicable
          telemarketing and messaging laws (including honoring opt-outs).
        </li>
        <li>Review conversations and respond to escalations and approval requests in a timely way.</li>
        <li>Keep your account credentials secure; you are responsible for activity under your account.</li>
      </ul>

      <h2>AI-generated content</h2>
      <p>
        Outside the fixed safety scripts, replies are generated by AI from your configuration and the
        customer&rsquo;s messages. AI output can be imperfect. The service is designed so that pricing and
        scheduling claims come only from the data you configure, and you control approval requirements — but
        you remain responsible for the commitments your business makes to its customers.
      </p>

      <h2>Billing</h2>
      <p>
        Paid plans are billed monthly through Stripe at the price shown when you subscribe. You can cancel at
        any time, effective at the end of the current billing period. Telephone numbers and carrier messaging
        fees may be billed separately where stated.
      </p>

      <h2>Acceptable use</h2>
      <p>
        No unlawful, deceptive, or abusive use; no spam or unsolicited marketing blasts; no attempting to
        breach or overload the service; no use of the service to send content you have no right to send.
      </p>

      <h2>Disclaimers and liability</h2>
      <p>
        The service is provided &ldquo;as is.&rdquo; To the maximum extent permitted by law, we disclaim
        implied warranties and are not liable for indirect, incidental, or consequential damages, or for
        missed messages, missed calls, or lost business opportunities. Our total liability for any claim is
        limited to the amounts you paid us in the twelve months before the claim.
      </p>

      <h2>Termination</h2>
      <p>
        You may close your account at any time. We may suspend or terminate accounts that violate these
        terms. On termination you may request an export of your data within 30 days.
      </p>

      <h2>Changes and contact</h2>
      <p>
        We may update these terms; material changes will be reflected by the date above, and continued use
        after changes means acceptance. Questions:{" "}
        <a href="mailto:support@myworkflo.com" className="text-accent-blue">
          support@myworkflo.com
        </a>
        .
      </p>
    </LegalPage>
  );
}
